version: "3.9"

services:
  gateway:
    image: ghcr.io/phillredkin/bakalarka-xai-moderation/gateway:${TAG:-latest}
    build:
      context: ../gateway
    ports:
      - "8080:80"
    environment:
      APP_ENV: ${APP_ENV:-test}
      TEXT_SERVICE_URL: http://text-service:8000/analyze
      IMAGE_SERVICE_URL: http://image-service:8000/analyze
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_TTL: 300
      RATE_LIMIT_PER_MIN: 60
      SIGHTENGINE_API_USER: ${SIGHTENGINE_API_USER}
      SIGHTENGINE_API_KEY: ${SIGHTENGINE_API_KEY}
    depends_on:
      - text-service
      - redis
    networks:
      - appnet

  text-service:
    image: ghcr.io/phillredkin/bakalarka-xai-moderation/text-service:${TAG:-latest}
    build:
      context: ../services/text-service
    ports:
      - "8001:8000"
    networks:
      - appnet
    environment:
      HF_TOKEN: ${HF_TOKEN}
  
  audio-service:
    image: ghcr.io/phillredkin/bakalarka-xai-moderation/audio-service:${TAG:-latest}
    build:
      context: ../services/audio-service
    ports:
      - "8002:8000"
    networks:
      - appnet

  image-service:
    image: ghcr.io/phillredkin/bakalarka-xai-moderation/image-service:${TAG:-latest}
    build:
      context: ../services/image-service
    ports:
      - "8003:8000"
    networks:
      - appnet
    environment:
      OCR_SPACE_API_KEY: ${OCR_SPACE_API_KEY}

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - appnet

networks:
  appnet:
    driver: bridge
